name: Move Issue to In Progress on Commit

on:
  push:
    branches:
      - '**/*'

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract issue number from branch name
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oP '(?<=\/)\d+')
        if [ -z "$ISSUE_NUMBER" ]; then
          echo "No issue number found in branch name"
          exit 1
        fi
        echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

    - name: Move issue to In Progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" \
        -X POST \
        -d '{"state":"open","labels":["in progress"]}' \
        https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}
