name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    if: contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'feature') || contains(github.event.issue.labels.*.name, 'chore') || contains(github.event.issue.labels.*.name, 'test') || contains(github.event.issue.labels.*.name, 'improvement') || contains(github.event.issue.labels.*.name, 'documentation')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create issue branch
      env:
         number: ${{ github.event.issue.number }}
         title: ${{ github.event.issue.title }}
         category: $(echo ${{ github.event.issue.labels.*.name }} | grep -E 'bug|feature|chore|test|improvement|documentation' | head -n 1)
      run: |
         title=${title// /-}
         branchname=${category}/${number}-$(echo $title | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
         git switch -c "$branchname"
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout -b $BRANCH_NAME
         git push origin $BRANCH_NAME
         git push -u origin "$branchname"
