name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    if: contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'feature') || contains(github.event.issue.labels.*.name, 'chore') || contains(github.event.issue.labels.*.name, 'test') || contains(github.event.issue.labels.*.name, 'improvement') || contains(github.event.issue.labels.*.name, 'documentation')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create issue branch
        env:
          number: ${{ github.event.issue.number }}
          category: ${{ toJSON(github.event.issue.labels.*.name) }}
          title: ${{ github.event.issue.title }}
        run: |
          title=${title// /-}
          category=$(echo $category | grep -Eo 'bug|feature|chore|test|improvement|documentation' | head -n 1)
          branchname=${category}/${number}-$(echo $title | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git switch -c "$branchname"
          git push -u origin "$branchname"
      
      - name: Add branch to issue comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"body\":\"Branch created: \`$branchname\`\"}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments
